### ISSUE TITLE
Fan Sensor not available after adding device with Tuya integration

### ISSUE THREAD

**Issue by dieantu** [dieantu/ha-config#3]
### The problem

Adding a "**KJ**" device from the Tuya integration creates a fan.{device} unavailable sensor.

Other 2 sensors are created with correct functionality:
switch.{device}_power
switch.{device}_filter_cartridge_reset

### What version of Home Assistant Core has the issue?

core-2021.11.1

### What was the last working version of Home Assistant Core?

Not tracked

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Tuya

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/tuya/

### Example YAML snippet

```yaml
JSON Configuration from Tuya IoT platform (JSON_EDITOR)

[
  {
    "code": "switch",
    "value": true
  },
  {
    "code": "fan_speed_enum",
    "value": "mid"
  },
  {
    "code": "light",
    "value": true
  },
  {
    "code": "filter_reset",
    "value": false
  }
]
```

### Anything in the logs that might be useful for us?

```txt
2021-11-08 11:14:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new fan.tuya entity: fan.purificador

2021-11-08 11:14:33 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 617, in state_attributes
    data[ATTR_SPEED] = self.speed
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 461, in speed
    if self._implemented_preset_mode and (preset_mode := self.preset_mode):
  File "/usr/src/homeassistant/homeassistant/components/tuya/fan.py", line 165, in preset_mode
    return self.device.status[DPCode.MODE]
KeyError: <DPCode.MODE: 'mode'>



2021-11-08 11:15:01 ERROR (MainThread) [homeassistant.util.logging] Exception in async_write_ha_state when dispatching 'tuya_entry_update_80256465f4cfa2c5ec84': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 617, in state_attributes
    data[ATTR_SPEED] = self.speed
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 461, in speed
    if self._implemented_preset_mode and (preset_mode := self.preset_mode):
  File "/usr/src/homeassistant/homeassistant/components/tuya/fan.py", line 165, in preset_mode
    return self.device.status[DPCode.MODE]
KeyError: <DPCode.MODE: 'mode'>
```

### Additional information

Device Information
Product Name: HIMOX-H06
Device ID: 80256465f4cfa2c5ec84
Product Category: kj
Device Status: Online

**Comment by dieantu** [comment]
Related:
https://github.com/home-assistant/core/issues/58933

**Comment by dieantu** [comment]
https://github.com/schonfeld/tuya-home-assistant/blob/master/custom_components/tuya_v2/fan.py
Possible .py to solve the issue
